"
" .vimrc
"   edited by Maxence Jacques de Dixmude
"

" Set UTF-8 as standard encoding and en_US
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
set ffs=unix,dos,mac	" Use Unix as the standard file type
set backspace=indent,eol,start
set nofixendofline
set noeol

syntax enable 			" Enable syntax highlighting
filetype off
filetype plugin indent on
filetype indent on
set autoindent			"New lines inherit the indentation of the previous lines
set smartindent

set nocompatible

" Appearance of VIM
set number				" Display the line number
set laststatus=2		" Always display the status bar
set t_Co=256

set mouse=a				" Enable mouse for scrolling and resizing
set history=1000		" Increase the undo limit

" Theme
syntax on
colorscheme dracula

" Backup disable
set nobackup
set nowb
set noswapfile

" Maintain undo history between sessions
set undofile
set undodir=~/.vim/undodir

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

set ru
set hid

set hlsearch			" Enable search highlighting
set ignorecase			" Ignore case when searching
set incsearch			" Incremental search that shows partial matches
set smartcase			" Automatically switch search to case-sensitive
set lazyredraw			" Don't redraw while executing macros

set ts=3
set tabstop=3
set shiftwidth=3
set softtabstop=3
set noexpandtab
set smarttab

set showmatch			" Show matching brackets when text indicator is over
set cursorline
set modelines=1

" Turn on the Wild menu
set wildmenu
set wildmode=full
set tabpagemax=50

" Ignore compiled files
set wildignore=*.o,*~,*.pyc,*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store

" Remove whitespaces on save
autocmd BufWritePre * :%s/\s\+$//e

" indent/unindent with tab/shift-tab
nmap <Tab> >>
nmap <S-tab> <<
imap <S-Tab> <Esc><<i
vmap <Tab> >gv
vmap <S-Tab> <gv

let python_highlight_all = 1
au BufNewFile,BufRead *.py set tabstop=3 softtabstop=3 shiftwidth=3 noexpandtab smarttab autoindent

""" EOF """
